### ISSUE TITLE
pflash is out of date and lacks (C) headers

### ISSUE THREAD

**Issue by ghost** [openbmc/skeleton#19]
(C) header problem will be fixed in skiboot 5.1.12

But you also have a copy of pflash from what looks like skiboot 5.0.x - which isn't really supported anymore.

**Comment by ghost** [comment]
I'm told by @shenki that the correct thing to do is package pflash in poky.

**Comment by nkskjames** [comment]
the problem is I use pflash as an API so I can expose on dbus the flashing capability which in turn exposes it to REST API.   so i had to copy it and pull all the exit's out and send proper dbus messages for progess and errors.  i realize we need a better long term strategy.  this whole repository is a stop gap anyway.

**Comment by ghost** [comment]
Why can't you use libflash?

**Comment by nkskjames** [comment]
libflash is not enough. you need ast-sf-ctrl and a couple of other headers in pflash directory.

**Comment by ghost** [comment]
Patches welcome :)

**Comment by nkskjames** [comment]
understand, i'll work on getting pflash out of this repository and use the one that poky would pull in.

**Comment by williamspatrick** [comment]
@bradbishop - Is this resolved with one of your pull requests?  I know we have recipes to build pflash from upstream skiboot now.

**Comment by bradbishop** [comment]
current state is that libflash/pflash are now packaged and available.  just need to forward port norms code.

Lets track that over here: https://github.com/openbmc/openbmc/issues/542
